# Generated by Django 3.0 on 2020-06-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debugtalks', '0004_remove_debugtalks_project'),
        ('projects', '0002_projects_debugtalk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='debugtalk',
            field=models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='debugtalks.DebugTalks'),
        ),
    ]
