# Generated by Django 3.0 on 2020-06-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debugtalks', '0004_remove_debugtalks_project'),
        ('projects', '0004_auto_20200619_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='debugtalk',
            field=models.ForeignKey(blank=True, help_text='所属项目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='debugtalks.DebugTalks'),
        ),
    ]
