# Generated by Django 3.0 on 2020-06-29 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debugtalks', '0005_auto_20200629_1034'),
        ('projects', '0006_auto_20200619_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='debugtalk',
            field=models.ForeignKey(blank=True, default=None, help_text='所属项目', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='debugtalks.DebugTalks'),
        ),
    ]
