# Generated by Django 3.0 on 2020-06-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envs',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
    ]
