# Generated by Django 3.0 on 2020-06-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsuits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuits',
            name='project',
        ),
    ]
