# Generated by Django 3.0 on 2020-06-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200629_1034'),
        ('locusts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locusts',
            name='project',
            field=models.ForeignKey(default=1, help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='locusts', to='projects.Projects'),
        ),
    ]
