# Generated by Django 3.0 on 2020-08-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interfacemocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='接口名称')),
                ('uri', models.CharField(max_length=256, verbose_name='uri')),
                ('description', models.TextField(blank=True, verbose_name='简要描述')),
                ('enabled', models.BooleanField(blank=True, default=False, verbose_name='启用/禁用')),
            ],
            options={
                'verbose_name': 'Mock接口',
                'verbose_name_plural': 'Mock接口',
                'db_table': 'tb_interfacemocks',
            },
        ),
    ]
