# Generated by Django 3.0 on 2020-06-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugtalks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugtalks',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
    ]
