# Generated by Django 3.0 on 2020-06-19 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('debugtalks', '0002_debugtalks_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debugtalks',
            name='project',
            field=models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='debugtalks', to='projects.Projects'),
        ),
    ]
