# Generated by Django 3.0 on 2020-06-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugtalks', '0004_remove_debugtalks_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debugtalks',
            name='name',
            field=models.CharField(default='debugtalk.py', help_text='debugtalk文件名称', max_length=200, unique=True, verbose_name='debugtalk文件名称'),
        ),
    ]
