# Generated by Django 3.0 on 2020-06-12 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('configures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configures',
            name='interface',
            field=models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='configures', to='projects.Projects'),
        ),
    ]
