# Generated by Django 3.0 on 2020-06-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configures', '0002_auto_20200612_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configures',
            old_name='interface',
            new_name='project',
        ),
    ]
