# Generated by Django 3.0 on 2020-06-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configures', '0003_auto_20200612_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configures',
            name='project',
        ),
    ]
